# Generated by Django 4.0 on 2021-12-17 07:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_clusterbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterbox',
            name='box',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
